### ISSUE TITLE
Some mistake on the camera-lidar odometry task

### ISSUE THREAD

**Issue by ZhengDonglei** [utiasASRL/pyboreas#47]
I want to experiment with whether this dataset can validate the fusion odometry method we proposed. Unfortunately, when processing sequence boreas-2020-12-18-13-44, we attempted to test the provided pose ground truth, but the results seem problematic. We computed a relatively accurate 3D point cloud result by processing the lidar data and its corresponding poses. 
![微信图片_20240424174843](https://github.com/utiasASRL/pyboreas/assets/96508673/9e804f13-909a-4cac-8019-cedc250b5f9a)

However, when we project the lidar points onto the camera coordinate system using the T_camera_lidar matrix, the projected points seem to have issues when using the camera pose, with significant drift occurring in many places. 
![微信图片_20240424174851](https://github.com/utiasASRL/pyboreas/assets/96508673/1deadf34-5ec1-4c2e-9421-cecc82fc7706)

Obviously, there is a problem with the T_camera_lidar matrix. Is there a suitable solution to address this tricky issue? Thank you.

**Comment by keenan-burnett** [comment]
Hello,

We have a python tutorial notebook for doing lidar projection onto a camera image. Can you have a look at that as a reference to fix your problem?

https://github.com/utiasASRL/pyboreas/blob/master/pyboreas/tutorials/lidar_camera_projection.ipynb

It's hard to tell what the problem is here without seeing your code.
